let customers=[];
const esc=v=>{const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML};
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(v||0));
const num=v=>Number(v||0).toLocaleString('en-IN');
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};
function sidebar(){const app=document.getElementById('app'),b=document.getElementById('sidebar-toggle');if(!app||!b)return;if(localStorage.getItem('sidebarCollapsed')==='true')app.classList.add('sidebar-collapsed');const sync=()=>{const c=app.classList.contains('sidebar-collapsed');b.querySelector('.toggle-icon').textContent=c?'›':'‹'};b.addEventListener('click',()=>{app.classList.toggle('sidebar-collapsed');localStorage.setItem('sidebarCollapsed',app.classList.contains('sidebar-collapsed')?'true':'false');sync()});sync()}
function render(list){const body=document.getElementById('customer-table-body');if(!body)return;if(!list.length){body.innerHTML='<tr><td colspan="8" class="loading">No customers found.</td></tr>';return}body.innerHTML=list.map(c=>{const id=String(c.customer_id||'');return `<tr><td><a class="customer-id-link" href="/customer-analysis.html?customer_id=${encodeURIComponent(id)}"><strong>${esc(id)}</strong></a></td><td>${num(c.cases)}</td><td class="amount">${money(c.amount_at_risk)}</td><td>${num(c.recovered_cases)}</td><td>${Number(c.recovery_rate||0).toFixed(2)}%</td><td class="amount">${money(c.money_recovered)}</td><td>${(Number(c.average_recovery_probability||0)*100).toFixed(2)}%</td><td><a class="view-btn" href="/customer-analysis.html?customer_id=${encodeURIComponent(id)}">View Customer</a></td></tr>`}).join('')}
async function loadCustomerMetrics(){try{const r=await fetch('/customers',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.detail||`Customers API ${r.status}`);customers=Array.isArray(d.customers)?d.customers:[];set('total-customers',num(d.total_customers));set('customers-with-cases',num(d.customers_with_cases));set('recovered-customers',num(d.recovered_customers));set('customer-money-recovered',money(d.money_recovered));render(customers)}catch(e){console.error(e);const b=document.getElementById('customer-table-body');if(b)b.innerHTML=`<tr><td colspan="8" class="loading">Unable to load customers: ${esc(e.message)}</td></tr>`}}
document.addEventListener('DOMContentLoaded',()=>{sidebar();loadCustomerMetrics();document.getElementById('customer-refresh')?.addEventListener('click',loadCustomerMetrics);document.getElementById('customer-search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();render(q?customers.filter(c=>String(c.customer_id||'').toLowerCase().includes(q)):customers)});setInterval(loadCustomerMetrics,30000)});
